"use client";
import Image from "next/image";
import { AnimatePresence, motion } from "framer-motion";
import { useEffect, useRef, useState } from "react";

const mainTikTok="https://www.tiktok.com/@maddie.brass", bookTikTok="https://www.tiktok.com/@brassbookclub", email="maddie@ugcbymaddie.com";
const reveal={initial:{opacity:0,y:32},whileInView:{opacity:1,y:0},viewport:{once:true,margin:"-80px"},transition:{duration:.75,ease:[.22,1,.36,1] as const}};
const Arrow=()=> <span className="arrow" aria-hidden>↗</span>;

function Nav(){const [open,setOpen]=useState(false);useEffect(()=>{document.body.style.overflow=open?"hidden":"";return()=>{document.body.style.overflow=""}},[open]);const links=[["Work","#work"],["Services","#services"],["Process","#process"],["About","#about"]];return <><a className="skip-link" href="#main">Skip to content</a><header className="site-nav"><a href="#top" className="wordmark">MADDIE <i>BRASS</i></a><nav className="desktop-links" aria-label="Primary">{links.map(([l,h])=><a key={h} href={h}>{l}</a>)}</nav><a className="nav-cta" href="#contact">Start a project <Arrow/></a><button className={`menu-button ${open?"is-open":""}`} onClick={()=>setOpen(!open)} aria-expanded={open} aria-label="Toggle navigation"><span/><span/></button></header><AnimatePresence>{open&&<motion.div className="mobile-menu" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}>{links.map(([l,h],i)=><motion.a key={h} href={h} onClick={()=>setOpen(false)} initial={{opacity:0,y:28}} animate={{opacity:1,y:0}} transition={{delay:.08*i}}>{l}</motion.a>)}<a href={`mailto:${email}`}>{email}</a></motion.div>}</AnimatePresence></>}

function VideoEmbed({id,title}:{id:string,title:string}){const host=useRef<HTMLDivElement>(null),[active,setActive]=useState(false),[ready,setReady]=useState(false);useEffect(()=>{const node=host.current;if(!node)return;const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){setActive(true);observer.disconnect()}},{rootMargin:"400px 0px"});observer.observe(node);return()=>observer.disconnect()},[]);return <div ref={host} className={`video-shell ${ready?"is-ready":""}`}><Image src={`/assets/videos/${id}.jpg`} fill sizes="(max-width:900px) 100vw, 31vw" alt={`Cover image for ${title}`} className="video-poster"/>{!active&&<button className="video-play" onClick={()=>setActive(true)} aria-label={`Load video: ${title}`}><span>▶</span><small>Play video</small></button>}{active&&<iframe src={`https://www.tiktok.com/player/v1/${id}?autoplay=0&loop=0&music_info=0&description=0&rel=0&native_context_menu=0`} title={title} loading="lazy" onLoad={()=>window.setTimeout(()=>setReady(true),1200)} allow="fullscreen; autoplay; encrypted-media; picture-in-picture" allowFullScreen/>}</div>}

const videos=[
 {id:"7672910964223659277",account:"maddie.brass",title:"The 10-minute outfit system",tag:"Organization · Problem / solution",copy:"A simple routine that removes a familiar morning frustration."},
 {id:"7672564151469739277",account:"maddie.brass",title:"A laundry upgrade that works",tag:"Home find · Product demo",copy:"Organization, wheels, handles, and a washable insert shown in use."},
 {id:"7673253893983276302",account:"maddie.brass",title:"Supportive can still be beautiful",tag:"Furniture · Lifestyle",copy:"A home-office chair presented through comfort, function, and style."},
 {id:"7673326905587715342",account:"maddie.brass",title:"Malinois approved",tag:"Pet-friendly home · Demo",copy:"A sturdy dog kennel that doubles as furniture and belongs in the room."},
 {id:"7670637444697541918",account:"brassbookclub",title:"The reading room at golden hour",tag:"Bookish lifestyle · Mood",copy:"Warm, sensory storytelling built around a real space and ritual."},
 {id:"7669155676085685534",account:"brassbookclub",title:"Finding the book girlies",tag:"BookTok · Community hook",copy:"A concise, personality-led post that earned genuine audience response."}];

export default function Home(){return <div id="top"><Nav/><main id="main">
<section className="hero section-shell"><motion.div className="hero-copy" initial={{opacity:0,y:28}} animate={{opacity:1,y:0}} transition={{duration:.9,ease:[.22,1,.36,1]}}><p className="eyebrow"><span/> Home + everyday lifestyle UGC</p><h1>Made for real life.<br/><em>Styled to stop</em> the scroll.</h1><p className="hero-body">I’m Maddie—a lifestyle creator turning useful finds, cozy moments, and everyday routines into content people want to watch, save, and shop.</p><div className="hero-actions"><a className="button button-dark" href="#contact">Start a project <Arrow/></a><a className="text-link" href="#work">Explore the work <span>↓</span></a></div></motion.div><motion.div className="portrait-stage" initial={{opacity:0,scale:.96,rotate:2}} animate={{opacity:1,scale:1,rotate:0}} transition={{duration:1,delay:.12,ease:[.22,1,.36,1]}}><div className="portrait-frame"><Image src="/assets/profiles/maddie-main.jpg" fill priority sizes="(max-width:768px) 92vw,43vw" alt="Maddie Brass, lifestyle and UGC creator"/></div><div className="stamp">UGC<br/><i>by Maddie</i><small>est. 2026</small></div><p className="scribble">your brand’s new<br/>favorite creative partner ↗</p></motion.div></section>
<div className="ticker"><div>HOME FINDS <i>✦</i> COZY ROUTINES <i>✦</i> BOOKISH LIFESTYLE <i>✦</i> PRODUCT DEMOS <i>✦</i> ORGANIC + PAID CREATIVE <i>✦</i></div></div>
<section id="work" className="work section-shell"><motion.div className="section-heading" {...reveal}><p className="kicker">01 / THE WORK</p><h2>Everyday products,<br/><em>made irresistible.</em></h2><p>Real posts from Maddie’s channels, built with a clear hook, a lived-in point of view, and the kind of polish that still feels native to the feed.</p></motion.div><div className="video-grid">{videos.map((x,i)=>{const videoUrl=`https://www.tiktok.com/@${x.account}/video/${x.id}`;return <motion.article key={x.id} className="video-card" {...reveal} transition={{...reveal.transition,delay:i*.05}}><VideoEmbed id={x.id} title={`${x.title} by @${x.account}`}/><div className="video-copy"><p>{x.tag}</p><h3>{x.title}</h3><span>{x.copy}</span><a href={videoUrl} target="_blank" rel="noreferrer">Open on TikTok <Arrow/></a></div></motion.article>})}</div><motion.div className="channel-links" {...reveal}><p>See more from Maddie.</p><a href={mainTikTok} target="_blank" rel="noreferrer"><Image src="/assets/profiles/maddie-main.jpg" width={56} height={56} alt=""/><span><small>SHOP FINDS + DAILY MUST-HAVES</small>@maddie.brass</span><Arrow/></a><a href={bookTikTok} target="_blank" rel="noreferrer"><Image src="/assets/profiles/maddie-books.jpg" width={56} height={56} alt=""/><span><small>BOOKTOK + COZY READING</small>@brassbookclub</span><Arrow/></a></motion.div></section>
<section id="about" className="about"><div className="section-shell about-grid"><motion.div className="about-portrait" {...reveal}><Image src="/assets/profiles/maddie-books.jpg" fill sizes="(max-width:768px) 100vw,38vw" alt="Maddie Brass smiling"/><span>real person.<br/>real home.<br/><i>real recommendation.</i></span></motion.div><motion.div className="about-copy" {...reveal}><p className="kicker light">02 / WHY MADDIE</p><h2>Good content doesn’t feel like an ad.</h2><p className="lead">It feels like the friend who already found the thing you were looking for.</p><p>That’s the sweet spot I create in: product-forward content with warmth, personality, and a real reason to care. From the first hook to the final detail shot, every choice helps your product feel useful, desirable, and at home.</p><div className="about-points"><span><b>01</b> A lived-in setting</span><span><b>02</b> A shopper’s instinct</span><span><b>03</b> A creator’s eye</span></div></motion.div></div></section>
<section id="services" className="services section-shell"><motion.div className="section-heading services-heading" {...reveal}><p className="kicker">03 / WAYS TO WORK TOGETHER</p><h2>Flexible deliverables.<br/><em>Clear creative.</em></h2></motion.div><div className="service-list">{[["01","Short-form UGC","Product-led vertical videos for TikTok, Reels, Shorts, organic social, or paid creative.","Concept · Filming · Edit · On-screen text"],["02","Lifestyle photography","Natural, shoppable images that make your product feel part of an actual routine.","Styling · Edited stills · Web + social crops"],["03","Creative variations","Build a stronger testing library from one production with more hooks, cuts, and formats.","Alt hooks · Cutdowns · Raw footage · Voiceover"],["04","Creator-posted partnerships","A separate, fit-first option for brands that belong naturally on Maddie’s own channels.","TikTok · Disclosure · Reporting as scoped"]].map(([n,t,c,m],i)=><motion.article key={n} {...reveal} transition={{...reveal.transition,delay:i*.05}}><span>{n}</span><h3>{t}</h3><p>{c}</p><small>{m}</small></motion.article>)}</div><p className="rights-note">Usage is scoped to the project. Paid ads, extended usage, raw footage, exclusivity, and additional versions are quoted separately.</p></section>
<section id="process" className="process section-shell"><motion.div className="section-heading" {...reveal}><p className="kicker">04 / THE PROCESS</p><h2>Easy from hello<br/><em>to handoff.</em></h2></motion.div><div className="steps">{[["1","Share the brief","Tell me about the product, goal, platform, timeline, and must-haves."],["2","Shape the concept","We align on the creative direction, deliverables, and usage before filming."],["3","Create + deliver","You receive polished, platform-ready assets through an organized handoff."]].map(([n,t,c])=><motion.div key={n} {...reveal}><b>{n}</b><h3>{t}</h3><p>{c}</p></motion.div>)}</div></section>
<section id="contact" className="contact"><motion.div className="contact-inner" {...reveal}><p className="kicker light">HAVE SOMETHING GOOD?</p><h2>Let’s make people<br/><em>want to bring it home.</em></h2><p>Send your product, campaign goal, timeline, and where the content will live. I’ll reply with the next best step.</p><a className="button button-cream" href={`mailto:${email}?subject=UGC Project Inquiry`}>Email Maddie <Arrow/></a><a className="contact-email" href={`mailto:${email}`}>{email}</a></motion.div></section></main>
<footer><a className="wordmark" href="#top">MADDIE <i>BRASS</i></a><p>Home + lifestyle UGC · ugcbymaddie.com</p><div><a href={mainTikTok}>TikTok</a><a href={bookTikTok}>BookTok</a><a href={`mailto:${email}`}>Email</a></div><small>© {new Date().getFullYear()} Maddie Brass</small></footer></div>}
