"use client";
import Image from "next/image";
import { AnimatePresence, motion } from "framer-motion";
import { useEffect, useState } from "react";

const mainTikTok="https://www.tiktok.com/@maddie.brass", bookTikTok="https://www.tiktok.com/@brassbookclub", email="maddie@ugcbymaddie.com";
const reveal={initial:{opacity:0,y:32},whileInView:{opacity:1,y:0},viewport:{once:true,margin:"-80px"},transition:{duration:.75,ease:[.22,1,.36,1] as const}};
const Arrow=()=> <span className="arrow" aria-hidden>↗</span>;

function Nav(){const [open,setOpen]=useState(false);useEffect(()=>{document.body.style.overflow=open?"hidden":"";return()=>{document.body.style.overflow=""}},[open]);const links=[["Work","#work"],["Services","#services"],["Process","#process"],["About","#about"]];return <><a className="skip-link" href="#main">Skip to content</a><header className="site-nav"><a href="#top" className="wordmark">MADDIE <i>BRASS</i></a><nav className="desktop-links" aria-label="Primary">{links.map(([l,h])=><a key={h} href={h}>{l}</a>)}</nav><a className="nav-cta" href="#contact">Start a project <Arrow/></a><button className={`menu-button ${open?"is-open":""}`} onClick={()=>setOpen(!open)} aria-expanded={open} aria-label="Toggle navigation"><span/><span/></button></header><AnimatePresence>{open&&<motion.div className="mobile-menu" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}>{links.map(([l,h],i)=><motion.a key={h} href={h} onClick={()=>setOpen(false)} initial={{opacity:0,y:28}} animate={{opacity:1,y:0}} transition={{delay:.08*i}}>{l}</motion.a>)}<a href={`mailto:${email}`}>{email}</a></motion.div>}</AnimatePresence></>}

const concepts=[
 {no:"01",title:"Daily must-haves",tag:"Home finds · Demo",copy:"Useful products, shown simply—the problem, the proof, and why it earns a place at home.",tone:"clay"},
 {no:"02",title:"A routine worth copying",tag:"Lifestyle · Voiceover",copy:"Warm, familiar routines that make a product feel natural instead of placed.",tone:"ink"},
 {no:"03",title:"Books worth staying in for",tag:"Bookish lifestyle · Mood",copy:"Cozy, story-led creative for books, reading accessories, and slow-living brands.",tone:"rose"},
 {no:"04",title:"Small upgrade, big difference",tag:"Home · Before / after",copy:"A quick visual transformation made for hooks, cutdowns, and paid-social testing.",tone:"sage"}];

export default function Home(){return <div id="top"><Nav/><main id="main">
<section className="hero section-shell"><motion.div className="hero-copy" initial={{opacity:0,y:28}} animate={{opacity:1,y:0}} transition={{duration:.9,ease:[.22,1,.36,1]}}><p className="eyebrow"><span/> Home + everyday lifestyle UGC</p><h1>Made for real life.<br/><em>Styled to stop</em> the scroll.</h1><p className="hero-body">I’m Maddie—a lifestyle creator turning useful finds, cozy moments, and everyday routines into content people want to watch, save, and shop.</p><div className="hero-actions"><a className="button button-dark" href="#contact">Start a project <Arrow/></a><a className="text-link" href="#work">Explore the work <span>↓</span></a></div></motion.div><motion.div className="portrait-stage" initial={{opacity:0,scale:.96,rotate:2}} animate={{opacity:1,scale:1,rotate:0}} transition={{duration:1,delay:.12,ease:[.22,1,.36,1]}}><div className="portrait-frame"><Image src="/assets/profiles/maddie-main.jpg" fill priority sizes="(max-width:768px) 92vw,43vw" alt="Maddie Brass, lifestyle and UGC creator"/></div><div className="stamp">UGC<br/><i>by Maddie</i><small>est. 2026</small></div><p className="scribble">your brand’s new<br/>favorite creative partner ↗</p></motion.div></section>
<div className="ticker"><div>HOME FINDS <i>✦</i> COZY ROUTINES <i>✦</i> BOOKISH LIFESTYLE <i>✦</i> PRODUCT DEMOS <i>✦</i> ORGANIC + PAID CREATIVE <i>✦</i></div></div>
<section id="work" className="work section-shell"><motion.div className="section-heading" {...reveal}><p className="kicker">01 / THE WORK</p><h2>Everyday products,<br/><em>made irresistible.</em></h2><p>Content with a clear hook, a lived-in point of view, and enough polish to feel special—without losing what makes it native to the feed.</p></motion.div><div className="concept-grid">{concepts.map((x,i)=><motion.article key={x.no} className={`concept-card ${x.tone}`} {...reveal} transition={{...reveal.transition,delay:i*.07}}><div className="concept-visual"><span>{x.no}</span><div className="shape"/><b>PLAY<br/>THE<br/>MOMENT</b></div><div className="concept-copy"><p>{x.tag}</p><h3>{x.title}</h3><span>{x.copy}</span></div></motion.article>)}</div><motion.div className="channel-links" {...reveal}><p>See Maddie in her natural habitat.</p><a href={mainTikTok} target="_blank" rel="noreferrer"><Image src="/assets/profiles/maddie-main.jpg" width={56} height={56} alt=""/><span><small>SHOP FINDS + DAILY MUST-HAVES</small>@maddie.brass</span><Arrow/></a><a href={bookTikTok} target="_blank" rel="noreferrer"><Image src="/assets/profiles/maddie-books.jpg" width={56} height={56} alt=""/><span><small>BOOKTOK + COZY READING</small>@brassbookclub</span><Arrow/></a></motion.div></section>
<section id="about" className="about"><div className="section-shell about-grid"><motion.div className="about-portrait" {...reveal}><Image src="/assets/profiles/maddie-books.jpg" fill sizes="(max-width:768px) 100vw,38vw" alt="Maddie Brass smiling"/><span>real person.<br/>real home.<br/><i>real recommendation.</i></span></motion.div><motion.div className="about-copy" {...reveal}><p className="kicker light">02 / WHY MADDIE</p><h2>Good content doesn’t feel like an ad.</h2><p className="lead">It feels like the friend who already found the thing you were looking for.</p><p>That’s the sweet spot I create in: product-forward content with warmth, personality, and a real reason to care. From the first hook to the final detail shot, every choice helps your product feel useful, desirable, and at home.</p><div className="about-points"><span><b>01</b> A lived-in setting</span><span><b>02</b> A shopper’s instinct</span><span><b>03</b> A creator’s eye</span></div></motion.div></div></section>
<section id="services" className="services section-shell"><motion.div className="section-heading services-heading" {...reveal}><p className="kicker">03 / WAYS TO WORK TOGETHER</p><h2>Flexible deliverables.<br/><em>Clear creative.</em></h2></motion.div><div className="service-list">{[["01","Short-form UGC","Product-led vertical videos for TikTok, Reels, Shorts, organic social, or paid creative.","Concept · Filming · Edit · On-screen text"],["02","Lifestyle photography","Natural, shoppable images that make your product feel part of an actual routine.","Styling · Edited stills · Web + social crops"],["03","Creative variations","Build a stronger testing library from one production with more hooks, cuts, and formats.","Alt hooks · Cutdowns · Raw footage · Voiceover"],["04","Creator-posted partnerships","A separate, fit-first option for brands that belong naturally on Maddie’s own channels.","TikTok · Disclosure · Reporting as scoped"]].map(([n,t,c,m],i)=><motion.article key={n} {...reveal} transition={{...reveal.transition,delay:i*.05}}><span>{n}</span><h3>{t}</h3><p>{c}</p><small>{m}</small></motion.article>)}</div><p className="rights-note">Usage is scoped to the project. Paid ads, extended usage, raw footage, exclusivity, and additional versions are quoted separately.</p></section>
<section id="process" className="process section-shell"><motion.div className="section-heading" {...reveal}><p className="kicker">04 / THE PROCESS</p><h2>Easy from hello<br/><em>to handoff.</em></h2></motion.div><div className="steps">{[["1","Share the brief","Tell me about the product, goal, platform, timeline, and must-haves."],["2","Shape the concept","We align on the creative direction, deliverables, and usage before filming."],["3","Create + deliver","You receive polished, platform-ready assets through an organized handoff."]].map(([n,t,c])=><motion.div key={n} {...reveal}><b>{n}</b><h3>{t}</h3><p>{c}</p></motion.div>)}</div></section>
<section id="contact" className="contact"><motion.div className="contact-inner" {...reveal}><p className="kicker light">HAVE SOMETHING GOOD?</p><h2>Let’s make people<br/><em>want to bring it home.</em></h2><p>Send your product, campaign goal, timeline, and where the content will live. I’ll reply with the next best step.</p><a className="button button-cream" href={`mailto:${email}?subject=UGC Project Inquiry`}>Email Maddie <Arrow/></a><a className="contact-email" href={`mailto:${email}`}>{email}</a></motion.div></section></main>
<footer><a className="wordmark" href="#top">MADDIE <i>BRASS</i></a><p>Home + lifestyle UGC · ugcbymaddie.com</p><div><a href={mainTikTok}>TikTok</a><a href={bookTikTok}>BookTok</a><a href={`mailto:${email}`}>Email</a></div><small>© {new Date().getFullYear()} Maddie Brass</small></footer></div>}
